#!/bin/sh

echo "⏳ Running code formatter before push..."

# Format code
npm run format

if [ $? -ne 0 ]; then
  echo "❌ Formatting failed. Push aborted."
  exit 1
fi

echo "✅ Code formatted successfully. Proceeding with push..."
exit 0
